// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;
using System.ComponentModel;

namespace ChronicKidneyDiseasePredictionApplicationML.Model
{
    public class ModelInput
    {
        [DisplayName("Age")]
        [ColumnName("Age"), LoadColumn(0)]
        public float Age { get; set; }

        [DisplayName("Blood Pressure (BP)")]
        [ColumnName("Blood Pressure (BP)"), LoadColumn(1)]
        public float Bp { get; set; }

        [DisplayName("Specific Gravity (SG)")]
        [ColumnName("Specific Gravity (SG)"), LoadColumn(2)]
        public float Sg { get; set; }

        [DisplayName("Albumin (AL)")]
        [ColumnName("Albumin (AL)"), LoadColumn(3)]
        public float Al { get; set; }

        [DisplayName("Sugar (SU)")]
        [ColumnName("Sugar (SU)"), LoadColumn(4)]
        public float Su { get; set; }

        [DisplayName("Red Blood Cells (RBC)")]
        [ColumnName("Red Blood Cells (RBC)"), LoadColumn(5)]
        public string Rbc { get; set; }

        [DisplayName("Pus Cell (PC)")]
        [ColumnName("Pus Cell (PC)"), LoadColumn(6)]
        public string Pc { get; set; }

        [DisplayName("Pus Cell Clumps (PCC)")]
        [ColumnName("Pus Cell Clumps (PCC)"), LoadColumn(7)]
        public string Pcc { get; set; }

        [DisplayName("Bacteria (BA)")]
        [ColumnName("Bacteria (BA)"), LoadColumn(8)]
        public string Ba { get; set; }

        [DisplayName("Blood Glucose Random (BGR)")]
        [ColumnName("Blood Glucose Random (BGR)"), LoadColumn(9)]
        public float Bgr { get; set; }

        [DisplayName("Blodd Urea (BU)")]
        [ColumnName("Blodd Urea (BU)"), LoadColumn(10)]
        public float Bu { get; set; }

        [DisplayName("Serum Creatinine (SC)")]
        [ColumnName("Serum Creatinine (SC)"), LoadColumn(11)]
        public float Sc { get; set; }

        [DisplayName("Sodium (SOD)")]
        [ColumnName("Sodium (SOD)"), LoadColumn(12)]
        public float Sod { get; set; }

        [DisplayName("Potassium (POT)")]
        [ColumnName("Potassium (POT)"), LoadColumn(13)]
        public float Pot { get; set; }

        [DisplayName("Hemoglobin (Hemo)")]
        [ColumnName("Hemoglobin (Hemo)"), LoadColumn(14)]
        public float Hemo { get; set; }

        [DisplayName("Packed Cell Volume (PCV)")]
        [ColumnName("Packed Cell Volume (PCV)"), LoadColumn(15)]
        public string Pcv { get; set; }

        [DisplayName("White Blodd Cell Count(WBCC)")]
        [ColumnName("White Blodd Cell Count (WBCC)"), LoadColumn(16)]
        public string Wbcc { get; set; }

        [DisplayName("Red Blodd Cell Count (RBCC)")]
        [ColumnName("Red Blodd Cell Count (RBCC)"), LoadColumn(17)]
        public float Rbcc { get; set; }

        [DisplayName("Hypertension (HTN)")]
        [ColumnName("Hypertension (HTN)"), LoadColumn(18)]
        public bool Htn { get; set; }

        [DisplayName("Diabeted Mellitus (DM)")]
        [ColumnName("Diabeted Mellitus (DM)"), LoadColumn(19)]
        public bool Dm { get; set; }

        [DisplayName("Coronary Artery Disease (CAD)")]
        [ColumnName("Coronary Artery Disease (CAD)"), LoadColumn(20)]
        public bool Cad { get; set; }

        [DisplayName("Appetite (APPET)")]
        [ColumnName("Appetite (APPET)"), LoadColumn(21)]
        public string Appet { get; set; }

        [DisplayName("Pedal Edema (PE)")]
        [ColumnName("Pedal Edema (PE)"), LoadColumn(22)]
        public bool Pe { get; set; }

        [DisplayName("Anemia (ANE)")]
        [ColumnName("Anemia (ANE)"), LoadColumn(23)]
        public bool Ane { get; set; }

        [DisplayName("Class")]
        [ColumnName("Class"), LoadColumn(24)]
        public float Class { get; set; }


    }
}
